name: Use Secrets

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Use secret

        run: |

          echo "Username is ${{ vars.set }}"

          echo "Password length is ${#set}"

        env:

          set: ${{ secrets.SECRET1}}
      - name: Use secret

        run: |

          echo "Username is ${{ secrets.SECRET1 }}"

          echo "Password length is ${#SECRET1}"

        env:

          set: ${{ secrets.SECRET1}}
